# -*- coding: utf-8 -*-
"""crop-scans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nLAxPzzqUyuymczUJMteuajTyCkSYdMt
"""

from PIL import Image
import glob
import os
from google.colab import drive

drive.mount('/content/drive')
files = glob.glob("/content/drive/My Drive/UCLA/F20-171/cyanotypes/tiff/all/*.tif")
dim = 2048

for file in files:
  filename = os.path.splitext(os.path.basename(file))[0]
  cyanotype = Image.open(file)
  width, height = cyanotype.size
  rows = int(height/dim)
  cols = int(width/dim)

  for j in range(0, rows, 1):
    for i in range(0, cols, 1):
      y = j*dim
      x = i*dim

      bounds = (x, y, x+dim, y+dim)
      cropped = cyanotype.crop(bounds)
      cropped.save("/content/drive/My Drive/UCLA/F20-171/cyanotypes/tiff/all/cropped/"+filename+"-col"+str(i)+"row"+str(j)+".jpg", "JPEG")